FROM node:18

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app


# Bundle app source
COPY ./my-dev-portal /usr/src/app

# Remove env file
RUN rm -f /usr/src/app/.env

# Make entrypoint script executable.
RUN chmod +x /usr/src/app/entrypoint.sh

EXPOSE 4000
ENTRYPOINT ["./entrypoint.sh"]